name: Update README

on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight UTC
    - cron: "0 12 * * *" # Runs at noon UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          # Update the "Last updated" date in the README.md
          sed -i "s/<!--Last updated:.*-->/<!--Last updated: $(date) -->/" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'jarrodramsey'
          git config --global user.email 'jarrod@jarrodramsey.com'
          git add README.md
          git commit -m "Update README with the latest date"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
